// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHP8V-SoTtFPbE0cUse5vV3lhVomvJQEA',
    appId: '1:680168932940:web:47485d9e420506f4f456e9',
    messagingSenderId: '680168932940',
    projectId: 'gatrakarsa',
    authDomain: 'gatrakarsa.firebaseapp.com',
    storageBucket: 'gatrakarsa.firebasestorage.app',
    measurementId: 'G-N6N9G5Z4R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dXkfb5mzr8DY91fiLWwEoPnghyULJHY',
    appId: '1:680168932940:android:8152e7fe068b8dd7f456e9',
    messagingSenderId: '680168932940',
    projectId: 'gatrakarsa',
    storageBucket: 'gatrakarsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXnLvIBIu9J7puhhOlUf6QbKZMKkD7LFk',
    appId: '1:680168932940:ios:03afd23b9014adf8f456e9',
    messagingSenderId: '680168932940',
    projectId: 'gatrakarsa',
    storageBucket: 'gatrakarsa.firebasestorage.app',
    iosBundleId: 'com.example.gatrakarsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXnLvIBIu9J7puhhOlUf6QbKZMKkD7LFk',
    appId: '1:680168932940:ios:03afd23b9014adf8f456e9',
    messagingSenderId: '680168932940',
    projectId: 'gatrakarsa',
    storageBucket: 'gatrakarsa.firebasestorage.app',
    iosBundleId: 'com.example.gatrakarsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHP8V-SoTtFPbE0cUse5vV3lhVomvJQEA',
    appId: '1:680168932940:web:f7fc131e5532a1a2f456e9',
    messagingSenderId: '680168932940',
    projectId: 'gatrakarsa',
    authDomain: 'gatrakarsa.firebaseapp.com',
    storageBucket: 'gatrakarsa.firebasestorage.app',
    measurementId: 'G-M5RPWWFS1L',
  );
}
